### ISSUE TITLE
Add EPIC new UI Library

### ISSUE THREAD

**Issue by MirayXS** [bloodball/UI-Librarys#6]
# Add EPIC new UI Library

Please add it before it gets deleted, i think it would get deleted soon sooo
it has all the information you need  ( docs  )

https://forum.robloxscripts.com/Thread-PREMIUM-RELEASE-Vape-Ui-Library-Open-Source

**Comment by yoitstactic123** [comment]
funny thing

I made the ui lib then they stole it off me so I doubt he will put a skidded ui lib in here
